nomad_zip:
  url: "https://releases.hashicorp.com/nomad/0.9.5/nomad_0.9.5_linux_amd64.zip"
  checksum: "9a137abad26959b6c5f8169121f1c7082dff7b11b11c7fe5a728deac7d4bd33f"

install_dir: "/usr/local/bin"
config_dir: "/etc/nomad.d"
systemd_config_dir: "/etc/systemd/system"
