- include_vars: "../vars/{{ stage_env }}.yml"

- name: Get Nomad Zipfile
  get_url: 
    url: "{{ nomad_zip.url }}"
    dest: /tmp/nomad.zip
    sha256sum: "{{ nomad_zip.checksum }}"

- name: Unarchive nomad zip
  unarchive:
    remote_src: yes
    src: /tmp/nomad.zip
    dest: "{{ install_dir }}"

- name: Create Nomad Configration Dir
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Nomad Data Dir
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Distribute Nomad Config
  template: 
    src: ../templates/agent.hcl.j2
    dest: "{{ config_dir }}/agent.hcl"

- name: Distribute Nomad Service Config
  template: 
    src: ../templates/nomad.service.j2
    dest: "{{ systemd_config_dir }}/nomad.service"

- name: Restart Nomad Service
  systemd:
    name: nomad.service
    state: restarted
    daemon_reload: yes
    enabled: yes
